python /home/tylerkershner/app/scripts/scrape_reddit.py gifs 
python /home/tylerkershner/app/scripts/scrape_reddit.py blackpeoplegifs 
python /home/tylerkershner/app/scripts/scrape_reddit.py SpaceGifs 
python /home/tylerkershner/app/scripts/scrape_reddit.py physicsgifs 
python /home/tylerkershner/app/scripts/scrape_reddit.py educationalgifs 
python /home/tylerkershner/app/scripts/scrape_reddit.py chemicalreactiongifs 
python /home/tylerkershner/app/scripts/scrape_reddit.py SurrealGifs 
python /home/tylerkershner/app/scripts/scrape_reddit.py Puggifs 
python /home/tylerkershner/app/scripts/scrape_reddit.py slothgifs 
python /home/tylerkershner/app/scripts/scrape_reddit.py asianpeoplegifs 
python /home/tylerkershner/app/scripts/scrape_reddit.py gaming_gifs 
python /home/tylerkershner/app/scripts/scrape_reddit.py Movie_GIFs 
python /home/tylerkershner/app/scripts/scrape_reddit.py asianpeoplegifs 
python /home/tylerkershner/app/scripts/scrape_reddit.py funnygifs 
python /home/tylerkershner/app/scripts/scrape_reddit.py wheredidthesodago 
python /home/tylerkershner/app/scripts/scrape_reddit.py reactiongifs 
python /home/tylerkershner/app/scripts/scrape_reddit.py creepy_gif 
python /home/tylerkershner/app/scripts/scrape_reddit.py perfectloops 
python /home/tylerkershner/app/scripts/scrape_reddit.py aww_gifs 
python /home/tylerkershner/app/scripts/scrape_reddit.py AnimalsBeingJerks 
python /home/tylerkershner/app/scripts/scrape_reddit.py AnimalGIFs 
python /home/tylerkershner/app/scripts/scrape_reddit.py whitepeoplegifs 